# Generated by Django 5.1 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("multi_player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="game_opponent",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="game",
            name="game_creator",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
